# Leitplanken für Copilot-Vorschläge im Repo
version: 1
language_guidance:
  kotlin:
    style: |
      - Bevorzuge Jetpack Compose + Material3.
      - Coroutines + Flow statt LiveData.
      - Unidirectional Data Flow, State als data class.
      - Keine globalen Singletons; konstruktive DI.
      - MinSdk 26, targetSdk 34, Kotlin 2.0.20.
    patterns_to_prefer:
      - androidx.compose.*
      - kotlinx.coroutines.*
      - androidx.navigation.*
      - androidx.room.*
    patterns_to_avoid:
      - GlobalScope
      - runBlocking im UI-Code
      - veraltete AppCompat-UI für neue Screens
  yaml:
    style: |
      - GitHub Actions: upload/download-artifact@v4, checkout@v4, setup-java@v4.
      - Runner ubuntu-22.04, IPv4 bevorzugen (siehe Workflows).
files:
  ignore:
    - "**/build/**"
    - "**/.gradle/**"
    - "**/*.keystore"
    - "**/local.properties"
guidance:
  general: |
    - Schreibe idiomatischen Kotlin-Code mit klaren KDoc-Kommentaren.
    - Liefere lauffähige, compilierbare Snippets – keine Pseudocode-Stubs.
    - Bevorzuge kleine, testbare Einheiten, trenne UI/Domain/Data.