name: Android Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/gradle-build-action@v3

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/**
            **/build/reports/tests/**
          retention-days: 7
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/gradle-build-action@v3

      - name: Run Lint
        run: ./gradlew lint --stacktrace

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            **/build/reports/lint-results*.* 
            **/build/reports/lint/**
          retention-days: 7
          if-no-files-found: warn
