name: Android Room CI

on:
  pull_request:
    paths-ignore: [ "**.md" ]
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]

permissions:
  contents: read

jobs:
  room-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Cache Android build tools (optional)
        run: echo "Gradle action handled cache."

      - name: Run Unit Tests (incl. Room)
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Verify Room schemas are committed
        run: |
          if [ -d app/schemas ] || [ -d schemas ]; then
            git add -A
            git diff --exit-code --name-only -- app/schemas schemas || { 
              echo "::error::Room schema hat sich geändert. Bitte Schemas committen."; 
              exit 1; 
            }
          else
            echo "Kein Schema-Ordner gefunden – check übersprungen."
          fi

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: room-unit-test-reports
          path: |
            **/build/test-results/**
            **/build/reports/tests/**
          retention-days: 7
          if-no-files-found: warn
