name: Android Tests (unit + lint)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-and-lint:
    # 22.04 ist aktuell stabiler als ubuntu-latest (24.04) bzgl. IPv6/CDN
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    env:
      # erzwinge IPv4 für alle Gradle/HTTP Calls
      GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dfile.encoding=UTF-8"

    steps:
      # IPv6 komplett abschalten + IPv4 Präferenz erzwingen
      - name: Force IPv4 (disable IPv6)
        run: |
          echo 'precedence ::ffff:0:0/96  100' | sudo tee -a /etc/gai.conf
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      # kleines Netz-Warmup mit IPv4
      - name: Network warm-up (IPv4)
        run: |
          for i in {1..5}; do
            echo "Warmup try $i ..."
            if curl -4fsSL https://api.github.com/rate_limit > /dev/null; then
              echo "Network OK"; break
            fi
            sleep 3
          done

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # checkout mit Retries (Workaround gegen seltene CDN-Hänger)
      - name: Checkout (retry)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 2
          command: |
            echo "-> checkout"
            git --version
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (with cache)
        uses: gradle/gradle-build-action@v3

      # Build + Tests + Lint mit Retries
      - name: Build + Unit tests + Lint (retry)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 25
          command: |
            ./gradlew --stacktrace \
              clean \
              assembleDebug \
              testDebugUnitTest \
              lintDebug

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/**
            **/build/reports/tests/**
          retention-days: 7
          if-no-files-found: warn

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            **/build/reports/lint-results*.* 
            **/build/reports/lint/**
          retention-days: 7
          if-no-files-found: warn
