name: Android Tests (unit + lint)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-and-lint:
    runs-on: ubuntu-22.04         # <-- stabiler als ubuntu-latest (24.04)
    timeout-minutes: 45

    env:
      # Bevorzuge IPv4 in Gradle / JVM (wirkt beim Dependency-Download)
      GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dfile.encoding=UTF-8"

    steps:
      - name: Network warm-up (mit Retries)
        run: |
          for i in 1 2 3; do
            echo "Ping GitHub try $i..."
            curl -fsSL https://api.github.com/rate_limit > /dev/null && break || sleep 3
          done

      - name: Checkout (mit Retry)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 2
          command: |
            echo "Running checkout..."
            bash -lc 'git --version'
            gh --version || true
        # eigentlicher Checkout:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Gradle-Befehle mit Retry kapseln (flaky Netz -> wiederholen)
      - name: Build + Unit Tests + Lint (Retry)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 25
          command: |
            ./gradlew --stacktrace \
              clean \
              assembleDebug \
              testDebugUnitTest \
              lintDebug

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/**
            **/build/reports/tests/**
          retention-days: 7
          if-no-files-found: warn        # <-- keine harten Fehler, falls früh abgebrochen

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            **/build/reports/lint-results*.* 
            **/build/reports/lint/**
          retention-days: 7
          if-no-files-found: warn
