name: Android Instrumented Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  connected-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 55
    env:
      GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dfile.encoding=UTF-8"
      MOVEMENT_ANALYSIS_MODEL_URL: ${{ secrets.MOVEMENT_ANALYSIS_MODEL_URL }}
      MOVEMENT_ANALYSIS_MODEL_SHA256: ${{ secrets.MOVEMENT_ANALYSIS_MODEL_SHA256 }}
      USE_ONNX_MOVENET: true
    steps:
      - name: Force IPv4 (disable IPv6)
        run: |
          echo 'precedence ::ffff:0:0/96  100' | sudo tee -a /etc/gai.conf
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
      - name: Network warm-up (IPv4)
        run: |
          for i in {1..4}; do
            echo "Warmup try $i ..."
            if curl -4fsSL https://api.github.com/rate_limit > /dev/null; then
              echo "Network OK"; break
            fi
            sleep 3
          done
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/gradle-build-action@v3
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Ensure platforms & build-tools
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Run connected tests (API 30)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot
          disable-animations: true
          script: |
            ./gradlew --stacktrace \
              assembleDebug \
              assembleAndroidTest \
              connectedDebugAndroidTest
      - name: Collect benchmark artifact
        if: success()
        run: |
          find . -name pose_backend_latency_ci.csv -maxdepth 6 -print -exec cp {} benchmarks_pose_backend_latency_ci.csv \; || true
      - name: Upload benchmark latency CSV
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pose-backend-latency
          path: benchmarks_pose_backend_latency_ci.csv
          if-no-files-found: warn
      - name: Upload instrumented test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-test-reports
          path: |
            **/build/reports/androidTests/**
            **/build/outputs/androidTest-results/**
          retention-days: 7
          if-no-files-found: warn
