name: Auto Merge Dependabot

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge patch updates
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"

      - name: Auto-merge androidx minor updates
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-minor' && contains(steps.meta.outputs.dependency-names, 'androidx.') }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"

      - name: Auto-merge GitHub Actions patch updates
        if: ${{ steps.meta.outputs.package-ecosystem == 'github-actions' && steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"

      - name: Auto-merge junit patch updates
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' && contains(steps.meta.outputs.dependency-names, 'junit:junit') }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"
