name: ONNX Conversion

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/convert_to_onnx.py'
      - 'models/tflite/**'
      - '.github/workflows/onnx-convert.yml'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    env:
      GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dfile.encoding=UTF-8"
      MOVEMENT_ANALYSIS_MODEL_URL: ${{ secrets.MOVEMENT_ANALYSIS_MODEL_URL }}
      MOVEMENT_ANALYSIS_MODEL_SHA256: ${{ secrets.MOVEMENT_ANALYSIS_MODEL_SHA256 }}

    steps:
      - name: Force IPv4 (disable IPv6)
        run: |
          echo 'precedence ::ffff:0:0/96  100' | sudo tee -a /etc/gai.conf
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install conversion deps
        run: |
          python -m pip install --upgrade pip
          pip install tflite2onnx onnx

      - name: Fetch models (TFLite)
        run: bash scripts/fetch_models.sh

      - name: Verify base TFLite models
        run: ./gradlew :app:verifyModels --stacktrace

      - name: Convert to ONNX
        run: python scripts/convert_to_onnx.py

      - name: List ONNX outputs
        run: ls -lh models/onnx

      - name: Commit & push ONNX models
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain models/onnx)" ]; then
            git add models/onnx
            git commit -m "chore(onnx): update converted ONNX models"
            git push
          else
            echo "No ONNX changes to commit"
          fi

      - name: Upload ONNX artifacts
        uses: actions/upload-artifact@v4
        with:
          name: onnx-models
          path: models/onnx/*.onnx
          if-no-files-found: warn
          retention-days: 7
