name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/gradle-build-action@v3

      # Falls du signierst, setze hier deine Secrets (KS_*).
      # - name: Decode signing keystore
      #   run: |
      #     echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Build release AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            **/build/outputs/bundle/release/*.aab
            **/build/outputs/mapping/release/mapping.txt
          retention-days: 14
          if-no-files-found: error
